version: "2.1"
 
services:

  cron:
    image: cron:$VERSION_CRON
    restart: always
    network_mode: "host"
    volumes:
      - ./crontab.yaml:/root/crontab.yaml:Z
      - ./id_rsa:/root/.ssh/id_rsa:Z
      - ./id_rsa.pub:/root/.ssh/id_rsa.pub:Z
      - ./config:/root/.ssh/config:Z
      - ./scripts:/root/scripts:Z
